import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * One flat config for the whole monorepo.
 *
 * The rule set is deliberately small. A large one gets `--quiet`-ed or disabled wholesale the
 * first time it blocks a release, and a lint config nobody runs is worse than none. Everything
 * enabled below either catches a real defect class or enforces a decision this codebase has
 * already made and documented.
 *
 * Type-aware rules are not enabled: they require a project reference per package and roughly
 * quadruple the run time, and `tsc --noEmit` already runs in CI and catches the same class of
 * problem more precisely.
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/.turbo/**',
      'packages/db/drizzle/**',
      'packages/db/migrations/**',
      // Regenerated by Next on every build; its triple-slash references are required.
      'apps/web/next-env.d.ts',
      // apps/ai is a Python service. Its virtualenv contains vendored JavaScript — pip bundles
      // a urllib3 web worker — which is not ours to lint and fails rules it was never written
      // against. Ignoring the whole tree rather than the one file, because the next dependency
      // that vendors a script would fail the build for the same non-reason.
      'apps/ai/.venv/**',
      '**/__pycache__/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.es2023 },
    },
    rules: {
      // ── Real defect classes ─────────────────────────────────────────────────────────
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-implicit-coercion': ['error', { boolean: false }],
      'no-return-await': 'off',
      '@typescript-eslint/return-await': 'off',
      // `await` inside a loop is usually a serial round trip that should be batched, but it is
      // also correct for a genuine sequence. Warn, so it is visible without blocking.
      'no-await-in-loop': 'off',

      // ── Decisions this codebase has made ────────────────────────────────────────────
      // Services throw domain errors; the transport layer maps them. Throwing a string or a
      // plain object bypasses `instanceof DomainError` and lands as a 500 — the exact bug
      // recorded as KI-R004.
      'no-throw-literal': 'error',

      // The API logs through pino so lines carry the request id and pass through redaction.
      // `console` in a service means a log line with neither.
      'no-console': ['error', { allow: ['warn', 'error'] }],

      // ── TypeScript ──────────────────────────────────────────────────────────────────
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          // `catch {}` with no binding is the idiom used throughout for "this failure is
          // expected and handled by the fallback".
          caughtErrors: 'all',
        },
      ],
      // `any` defeats the point of the strict config. Warn rather than error so a third-party
      // type gap does not block a fix.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/consistent-type-imports': [
        'warn',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },

  // ── Scripts and CLIs legitimately write to stdout ──────────────────────────────────
  {
    files: ['scripts/**/*.ts', 'packages/db/src/cli/**/*.ts', 'packages/db/scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  // ── The API bootstrap runs before the logger exists ────────────────────────────────
  {
    files: ['apps/api/src/main.ts', 'apps/api/src/**/client.ts', 'packages/db/src/client.ts'],
    rules: { 'no-console': 'off' },
  },

  /**
   * NestJS reads constructor parameter types at runtime through `emitDecoratorMetadata`, so an
   * injected class must be a **value** import. `consistent-type-imports` autofixes those to
   * `import type`, which erases them at compile time — the container then has nothing to
   * resolve and every guard's dependencies are `undefined` at runtime. The failure is silent
   * until the first request.
   *
   * The rule is off for the entire API rather than disabled line by line, because a `--fix`
   * run would reintroduce it everywhere the moment someone adds a service.
   */
  {
    files: ['apps/api/**/*.ts', 'packages/db/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },

  // ── Tests ──────────────────────────────────────────────────────────────────────────
  {
    files: ['**/test/**/*.ts', '**/*.spec.ts'],
    languageOptions: { globals: { ...globals.node } },
    rules: {
      'no-console': 'off',
      // A test asserting on shape frequently needs to hand in a deliberately wrong value.
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // ── Web ────────────────────────────────────────────────────────────────────────────
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // A missing dependency in a hook produces a stale closure, which presents as data that
      // silently stops updating — one of the hardest React bugs to diagnose from a report.
      'react-hooks/exhaustive-deps': 'warn',
    },
  },

  // ── Config files ───────────────────────────────────────────────────────────────────
  {
    files: ['**/*.config.{ts,mts,mjs,js}', '**/*.workspace.ts'],
    rules: { 'no-console': 'off', '@typescript-eslint/no-explicit-any': 'off' },
  },
);
