/**
 * System role presets.
 *
 * These are seeded into every new tenant as a starting point. They are ordinary rows once
 * seeded — a school can edit them, clone them, or ignore them entirely and build its own.
 * Nothing in the codebase branches on `roleKey`; it exists for seeding, for the UI to show a
 * sensible label, and for support staff to talk about.
 *
 * The grants below are deliberately conservative. It is easy for an administrator to add a
 * permission when someone asks; it is very hard to notice that a role has quietly held
 * `finance.refund` for a year.
 */

import type { Permission } from './catalog';

export interface SystemRoleDefinition {
  key: string;
  nameEn: string;
  nameBn: string;
  description: string;
  /** Permission strings, possibly with trailing wildcards. */
  permissions: readonly (Permission | string)[];
  /** Which kind of person this role is for. Drives the invitation UI and default filters. */
  audience: 'staff' | 'teaching' | 'student' | 'guardian' | 'external';
  /**
   * A role that must not be granted casually. The UI shows a confirmation and the grant is
   * always audited.
   */
  sensitive: boolean;
}

const VIEW_ACADEMIC_STRUCTURE: readonly string[] = [
  'academic.years.view',
  'academic.classes.view',
  'academic.sections.view',
  'academic.subjects.view',
  'academic.calendar.view',
  'institution.view',
  'campus.view',
];

export const SYSTEM_ROLES: readonly SystemRoleDefinition[] = [
  {
    key: 'school_owner',
    nameEn: 'School Owner',
    nameBn: 'স্কুল মালিক',
    description:
      'Full control of the organization, including billing and role management. Typically one or two people.',
    audience: 'staff',
    sensitive: true,
    permissions: ['*'],
  },
  {
    key: 'chairman',
    nameEn: 'Chairman',
    nameBn: 'চেয়ারম্যান',
    description:
      'Governing-body oversight. Sees everything and approves high-value actions, but does not do day-to-day data entry.',
    audience: 'staff',
    sensitive: true,
    permissions: [
      'organization.view',
      'organization.billing.view',
      'institution.view',
      'campus.view',
      'settings.view',
      'audit.view',
      'academic.*',
      'students.view.all',
      'guardians.view.all',
      'attendance.view.all',
      'attendance.reports.view',
      'results.view.all',
      'results.reports.view',
      'finance.fees.view',
      'finance.invoices.view',
      'finance.ledger.view',
      'finance.reports.view',
      'finance.refund.approve',
      // Oversight, not bookkeeping: the chairman reviews and closes periods but does not
      // create the entries they would then be approving.
      'accounting.coa.view',
      'accounting.journal.view',
      'accounting.journal.post',
      'accounting.reports.view',
      'accounting.period.close',
      'hr.employees.view',
      'payroll.runs.view',
      'payroll.runs.approve',
      'reports.*',
      'workflows.act',
      'ai.copilot.use',
      'ai.principal_insights.view',
    ],
  },
  {
    key: 'principal',
    nameEn: 'Principal',
    nameBn: 'অধ্যক্ষ',
    description: 'Head of the institution. Broad operational authority across academics and staff.',
    audience: 'staff',
    sensitive: true,
    permissions: [
      'institution.view',
      'institution.update',
      'campus.view',
      'settings.view',
      'users.view',
      'users.invite',
      'users.assign_roles',
      'roles.view',
      'audit.view',
      'academic.*',
      'students.view.all',
      'students.create',
      'students.update',
      'students.archive',
      'students.promote',
      'students.transfer',
      'students.withdraw',
      'students.readmit',
      'students.export',
      'students.documents.view',
      'guardians.view.all',
      'guardians.update',
      'admissions.*',
      'timetable.*',
      'attendance.view.all',
      'attendance.correct',
      'attendance.correct.approve',
      'attendance.reports.view',
      'attendance.employee.view',
      'exams.*',
      'results.review',
      'results.approve',
      'results.publish',
      'results.unpublish',
      'results.view.all',
      'results.reports.view',
      'homework.view',
      'lms.view',
      'lms.view.all',
      'lms.publish',
      'finance.fees.view',
      'finance.invoices.view',
      'finance.discounts.approve',
      'finance.ledger.view',
      'finance.reports.view',
      'accounting.reports.view',
      'communication.*',
      'hr.employees.view',
      'hr.employees.update',
      'hr.contracts.manage',
      'hr.performance.manage',
      'leave.requests.view.all',
      'leave.requests.approve',
      'library.catalog.view',
      'transport.view',
      'discipline.*',
      'documents.generate',
      'documents.templates.manage',
      'reports.*',
      'workflows.*',
      'automation.rules.view',
      'ai.copilot.use',
      'ai.principal_insights.view',
      'ai.teacher_tools.use',
    ],
  },
  {
    key: 'vice_principal',
    nameEn: 'Vice Principal',
    nameBn: 'উপাধ্যক্ষ',
    description: 'Deputises for the principal on academics and discipline; no finance authority.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'academic.classes.manage',
      'academic.sections.manage',
      'academic.assignments.manage',
      'students.view.all',
      'students.update',
      'guardians.view.all',
      'timetable.view',
      'timetable.manage',
      'timetable.substitute',
      'attendance.view.all',
      'attendance.correct',
      'attendance.correct.approve',
      'attendance.reports.view',
      'exams.view',
      'exams.schedule.manage',
      'results.review',
      'results.view.all',
      'results.reports.view',
      'homework.view',
      'communication.send',
      'communication.notices.publish',
      'leave.requests.view.all',
      'leave.requests.approve',
      'discipline.*',
      'reports.view',
      'reports.export',
      'workflows.act',
      'ai.copilot.use',
    ],
  },
  {
    key: 'head_teacher',
    nameEn: 'Head Teacher',
    nameBn: 'প্রধান শিক্ষক',
    description: 'Leads a department or section. Reviews marks before they reach the controller.',
    audience: 'teaching',
    sensitive: false,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'academic.assignments.manage',
      'students.view.all',
      'attendance.view.all',
      'attendance.mark',
      'attendance.correct',
      'attendance.reports.view',
      'exams.view',
      'results.enter_marks',
      'results.submit_marks',
      'results.review',
      'results.view.all',
      'results.reports.view',
      'homework.*',
      'lms.*',
      'timetable.view',
      'timetable.substitute',
      'communication.send',
      'discipline.records.view',
      'discipline.records.create',
      'reports.view',
      'workflows.act',
      'ai.copilot.use',
      'ai.teacher_tools.use',
    ],
  },
  {
    key: 'administrator',
    nameEn: 'Administrator',
    nameBn: 'প্রশাসক',
    description:
      'Day-to-day office administration: records, users, documents. No marks entry, no payments.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'settings.view',
      'users.view',
      'users.create',
      'users.invite',
      'users.update',
      'roles.view',
      'students.view.all',
      'students.create',
      'students.update',
      'students.import',
      'students.export',
      'students.documents.view',
      'students.documents.manage',
      'guardians.view.all',
      'guardians.create',
      'guardians.update',
      'guardians.link_student',
      'attendance.view.all',
      'attendance.reports.view',
      'communication.send',
      'communication.notices.publish',
      'documents.generate',
      'reports.view',
      'reports.export',
    ],
  },
  {
    key: 'academic_coordinator',
    nameEn: 'Academic Coordinator',
    nameBn: 'একাডেমিক সমন্বয়ক',
    description: 'Owns the academic calendar, timetable and curriculum configuration.',
    audience: 'teaching',
    sensitive: false,
    permissions: [
      'academic.*',
      'institution.view',
      'campus.view',
      'students.view.all',
      'timetable.*',
      'attendance.view.all',
      'attendance.reports.view',
      'exams.view',
      'exams.manage',
      'exams.schedule.manage',
      'results.view.all',
      'results.reports.view',
      'homework.view',
      'lms.*',
      'reports.view',
      'reports.export',
      'ai.copilot.use',
      'ai.teacher_tools.use',
    ],
  },
  {
    key: 'admission_officer',
    nameEn: 'Admission Officer',
    nameBn: 'ভর্তি কর্মকর্তা',
    description: 'Runs the admission funnel from inquiry to enrolment.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'admissions.*',
      'students.view.all',
      'students.create',
      'students.documents.view',
      'students.documents.manage',
      'guardians.view.all',
      'guardians.create',
      'guardians.update',
      'guardians.link_student',
      'finance.invoices.view',
      'communication.send',
      'documents.generate',
      'reports.view',
    ],
  },
  {
    key: 'accountant',
    nameEn: 'Accountant',
    nameBn: 'হিসাবরক্ষক',
    description:
      'Collects fees and keeps the books. Cannot approve its own refunds and cannot touch marks.',
    audience: 'staff',
    sensitive: true,
    permissions: [
      'institution.view',
      'campus.view',
      'academic.years.view',
      'academic.classes.view',
      'academic.sections.view',
      'students.view.all',
      'guardians.view.all',
      'finance.fees.view',
      'finance.fees.manage',
      'finance.plans.manage',
      'finance.invoices.view',
      'finance.invoices.generate',
      'finance.discounts.manage',
      'finance.collect_payment',
      'finance.refund',
      'finance.ledger.view',
      'finance.reports.view',
      'accounting.coa.view',
      'accounting.journal.view',
      'accounting.journal.create',
      'accounting.reports.view',
      'accounting.reconcile',
      'inventory.view',
      'inventory.purchase.request',
      'documents.generate',
      'reports.view',
      'reports.export',
      'workflows.act',
    ],
  },
  {
    key: 'accounts_manager',
    nameEn: 'Accounts Manager',
    nameBn: 'হিসাব ব্যবস্থাপক',
    description: 'Supervises accounting. Approves refunds and posts journals.',
    audience: 'staff',
    sensitive: true,
    // Deliberately enumerated rather than `finance.*` / `accounting.*`. The wildcards granted
    // both sides of every separation-of-duties pair — this role could raise a refund and then
    // approve its own refund, which is exactly the control the pairing exists to provide. It
    // approves; the accountant initiates.
    permissions: [
      'institution.view',
      'campus.view',
      'students.view.all',
      'finance.fees.view',
      'finance.fees.manage',
      'finance.plans.manage',
      'finance.invoices.view',
      'finance.invoices.generate',
      'finance.invoices.void',
      'finance.discounts.approve',
      'finance.refund.approve',
      'finance.ledger.view',
      'finance.reports.view',
      'accounting.coa.view',
      'accounting.coa.manage',
      'accounting.journal.view',
      'accounting.journal.post',
      'accounting.journal.reverse',
      'accounting.reports.view',
      'accounting.budgets.manage',
      'accounting.reconcile',
      'accounting.period.close',
      'inventory.view',
      'inventory.purchase.approve',
      'payroll.runs.view',
      'documents.generate',
      'reports.*',
      'audit.view',
      'workflows.act',
      'ai.copilot.use',
    ],
  },
  {
    key: 'hr_manager',
    nameEn: 'HR Manager',
    nameBn: 'এইচআর ব্যবস্থাপক',
    description: 'Employee lifecycle, leave policy and payroll preparation.',
    audience: 'staff',
    sensitive: true,
    permissions: [
      'institution.view',
      'campus.view',
      'users.view',
      'users.invite',
      'users.create',
      'users.update',
      'users.deactivate',
      'hr.*',
      'attendance.employee.view',
      'attendance.employee.mark',
      'leave.*',
      'payroll.structures.manage',
      'payroll.runs.view',
      'payroll.runs.create',
      'payroll.payslips.view.all',
      'documents.generate',
      'reports.view',
      'reports.export',
      'workflows.act',
    ],
  },
  {
    key: 'examination_controller',
    nameEn: 'Examination Controller',
    nameBn: 'পরীক্ষা নিয়ন্ত্রক',
    description: 'Owns exams end to end, including approval and publication of results.',
    audience: 'staff',
    sensitive: true,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'students.view.all',
      'exams.*',
      'results.review',
      'results.approve',
      'results.publish',
      'results.unpublish',
      'results.correct',
      'results.view.all',
      'results.reports.view',
      'timetable.view',
      'documents.generate',
      'documents.templates.manage',
      'communication.send',
      'reports.view',
      'reports.export',
      'workflows.act',
      'ai.copilot.use',
    ],
  },
  {
    key: 'teacher',
    nameEn: 'Teacher',
    nameBn: 'শিক্ষক',
    description:
      'Subject teacher. Sees only the students in sections they are assigned to, and cannot publish results.',
    audience: 'teaching',
    sensitive: false,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'students.view.assigned',
      'attendance.view.assigned',
      'attendance.mark',
      'attendance.correct',
      'exams.view',
      'results.enter_marks',
      'results.submit_marks',
      'results.view.assigned',
      'homework.view',
      'homework.create',
      'homework.update',
      'homework.delete',
      'homework.grade',
      'lms.view',
      'lms.view.assigned',
      'lms.manage',
      'lms.progress.view',
      'timetable.view',
      'communication.send',
      'discipline.records.view',
      'discipline.records.create',
      'leave.requests.view.own',
      'leave.requests.create',
      'payroll.payslips.view.own',
      'documents.generate',
      'reports.view',
      'ai.teacher_tools.use',
      'ai.copilot.use',
    ],
  },
  {
    key: 'class_teacher',
    nameEn: 'Class Teacher',
    nameBn: 'শ্রেণি শিক্ষক',
    description:
      'Teacher with pastoral responsibility for one section: attendance corrections, guardian contact, leave approval.',
    audience: 'teaching',
    sensitive: false,
    permissions: [
      ...VIEW_ACADEMIC_STRUCTURE,
      'students.view.assigned',
      'students.update',
      'guardians.view.all',
      'attendance.view.assigned',
      'attendance.mark',
      'attendance.correct',
      'attendance.reports.view',
      'exams.view',
      'results.enter_marks',
      'results.submit_marks',
      'results.view.assigned',
      'results.reports.view',
      'homework.*',
      'lms.view',
      'lms.view.assigned',
      'lms.manage',
      'lms.progress.view',
      'timetable.view',
      'communication.send',
      'discipline.records.view',
      'discipline.records.create',
      'leave.requests.view.all',
      'leave.requests.approve',
      'leave.requests.create',
      'payroll.payslips.view.own',
      'documents.generate',
      'reports.view',
      'ai.teacher_tools.use',
      'ai.copilot.use',
    ],
  },
  {
    key: 'librarian',
    nameEn: 'Librarian',
    nameBn: 'গ্রন্থাগারিক',
    description: 'Library catalogue and circulation.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      'institution.view',
      'campus.view',
      'students.view.all',
      'library.*',
      'hr.employees.view',
      'reports.view',
      'leave.requests.view.own',
      'leave.requests.create',
      'payroll.payslips.view.own',
    ],
  },
  {
    key: 'transport_manager',
    nameEn: 'Transport Manager',
    nameBn: 'পরিবহন ব্যবস্থাপক',
    description: 'Routes, vehicles, drivers and student transport assignments.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      'institution.view',
      'campus.view',
      'students.view.all',
      'guardians.view.all',
      'transport.*',
      'communication.send',
      'reports.view',
      'leave.requests.view.own',
      'leave.requests.create',
      'payroll.payslips.view.own',
    ],
  },
  {
    key: 'inventory_manager',
    nameEn: 'Inventory Manager',
    nameBn: 'ইনভেন্টরি ব্যবস্থাপক',
    description: 'Stock, procurement and assets.',
    audience: 'staff',
    sensitive: false,
    // Enumerated rather than `inventory.*`: the wildcard let this role approve its own
    // purchase requisitions. Requesting is theirs; approving belongs to the accounts manager
    // or the principal, who hold the budget.
    permissions: [
      'institution.view',
      'campus.view',
      'inventory.view',
      'inventory.manage',
      'inventory.purchase.request',
      'inventory.receive',
      'assets.*',
      'reports.view',
      'workflows.act',
      'leave.requests.view.own',
      'leave.requests.create',
      'payroll.payslips.view.own',
    ],
  },
  {
    key: 'receptionist',
    nameEn: 'Receptionist',
    nameBn: 'রিসেপশনিস্ট',
    description:
      'Front desk. Can look up a student and log an inquiry, but cannot change academic or financial records.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      'institution.view',
      'campus.view',
      'academic.classes.view',
      'academic.sections.view',
      'students.view.all',
      'guardians.view.all',
      'attendance.view.all',
      'admissions.inquiries.view',
      'admissions.inquiries.manage',
      'communication.send',
      'leave.requests.view.own',
      'leave.requests.create',
      'payroll.payslips.view.own',
    ],
  },
  {
    key: 'security_officer',
    nameEn: 'Security Officer',
    nameBn: 'নিরাপত্তা কর্মকর্তা',
    description:
      'Gate entry and exit. Deliberately narrow — enough to identify a student at the gate, nothing more.',
    audience: 'staff',
    sensitive: false,
    permissions: [
      'institution.view',
      'campus.view',
      'students.view.all',
      'attendance.view.all',
      'attendance.mark',
      'transport.view',
      'leave.requests.view.own',
      'leave.requests.create',
      'payroll.payslips.view.own',
    ],
  },
  {
    key: 'student',
    nameEn: 'Student',
    nameBn: 'শিক্ষার্থী',
    description: 'Sees only their own records.',
    audience: 'student',
    sensitive: false,
    permissions: [
      'academic.calendar.view',
      'students.view.own',
      'attendance.view.own',
      'results.view.own',
      'homework.view',
      'homework.submit',
      'lms.view',
      'lms.view.own',
      'lms.submit',
      'timetable.view',
      'library.catalog.view',
      'finance.own.view',
      'documents.verify',
      'ai.tutor.use',
    ],
  },
  {
    key: 'guardian',
    nameEn: 'Guardian',
    nameBn: 'অভিভাবক',
    description:
      'Parent or guardian. Sees only the children explicitly linked to them, and only those.',
    audience: 'guardian',
    sensitive: false,
    permissions: [
      'academic.calendar.view',
      'students.view.own',
      'guardians.view.own',
      'attendance.view.own',
      'results.view.own',
      'homework.view',
      'lms.view',
      'lms.view.own',
      'timetable.view',
      'finance.own.view',
      'leave.requests.create',
      'leave.requests.view.own',
      'transport.view',
      'documents.verify',
    ],
  },
  {
    key: 'auditor',
    nameEn: 'Auditor',
    nameBn: 'নিরীক্ষক',
    description:
      'Read-only across finance and records, including the audit log. Cannot change anything, by construction.',
    audience: 'external',
    sensitive: true,
    permissions: [
      'organization.view',
      'institution.view',
      'campus.view',
      'settings.view',
      'audit.view',
      'audit.export',
      'academic.years.view',
      'academic.classes.view',
      'academic.sections.view',
      'students.view.all',
      'attendance.view.all',
      'attendance.reports.view',
      'results.view.all',
      'results.reports.view',
      'finance.fees.view',
      'finance.invoices.view',
      'finance.ledger.view',
      'finance.reports.view',
      'accounting.coa.view',
      'accounting.journal.view',
      'accounting.reports.view',
      'hr.employees.view',
      'payroll.runs.view',
      'inventory.view',
      'assets.view',
      'reports.view',
      'reports.export',
    ],
  },
];

export const SYSTEM_ROLE_KEYS = SYSTEM_ROLES.map((role) => role.key);

export function findSystemRole(key: string): SystemRoleDefinition | undefined {
  return SYSTEM_ROLES.find((role) => role.key === key);
}

/**
 * Roles a newly created tenant gets by default. The rest are available but not seeded, so a
 * small school's role list is not 24 items long on day one.
 */
export const DEFAULT_SEEDED_ROLE_KEYS: readonly string[] = [
  'school_owner',
  'principal',
  'administrator',
  'accountant',
  'examination_controller',
  'teacher',
  'class_teacher',
  'student',
  'guardian',
];
