/**
 * Document and certificate generation (Phase 23).
 *
 * This module renders official paper — transfer certificates, testimonials, salary
 * certificates, marksheets — from data that other modules own. It stores **no** copy of a
 * student, an employee or a guardian: a request names a subject by kind and id, and the
 * renderer reads through the owning module's scope rules at issue time.
 *
 * Four tables and the invariants that justify each of them:
 *
 *  1. **`document_templates` are versioned, never edited in place.** `(institution, key,
 *     version)` is unique and a version number is never reused. Editing an active template
 *     supersedes it with `version + 1`; every document already issued keeps the
 *     `template_version` it was rendered from, so reprinting a 2026 certificate in 2030
 *     cannot silently apply the 2030 wording. A partial unique index guarantees at most one
 *     *active* version per key.
 *
 *  2. **An issued document is immutable.** `rendered_html` and `data_snapshot` freeze at
 *     issue time. `issued_documents_immutable` (migration 0028) refuses every UPDATE except
 *     the one legal transition — revocation, which sets `revoked_at`, `revoked_by` and
 *     `revoked_reason` and touches nothing else — and refuses DELETE outright. Reissuing
 *     after the underlying record changes creates a *new* row with a new serial. This is the
 *     entire point of the module: a certificate asserts what was true on the day it was
 *     issued, and `data_snapshot` is that assertion, preserved verbatim.
 *
 *  3. **Four eyes on an approval, enforced by the database.**
 *     `document_requests_approver_not_requester` is a check constraint, not a service
 *     convention: a row whose `approved_by` equals its `requested_by` cannot exist, even if
 *     written by raw SQL by someone holding every permission in the catalogue.
 *
 *  4. **Verification is append-only.** `document_verifications` records each public check of
 *     a verification code; `document_verifications_append_only` refuses UPDATE and DELETE,
 *     for the same reason `audit_logs` does — a log that can be edited is not evidence.
 *
 * Serial numbers and verification codes are generated by the service from
 * `@shikkha/shared`'s crypto helpers (`humanCode`), never from `Math.random`, and are unique
 * per institution. The verification code additionally carries a global unique index: the
 * public verification endpoint is given a code and nothing else, so a code that resolved to
 * two documents in two tenants would be ambiguous rather than merely unlucky.
 *
 * `subject_id` deliberately carries **no** foreign key. It points at a student, an employee
 * or a guardian depending on `subject_kind`, and a polymorphic reference cannot be a real FK
 * without three nullable columns whose mutual exclusion would itself need a constraint. The
 * service resolves and scope-checks the subject on every read and write; an issued document
 * additionally holds its own snapshot, so it stays readable and truthful even if the subject
 * row is later archived.
 */

import { relations, sql } from 'drizzle-orm';
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';
import {
  actorColumns,
  archiveColumns,
  primaryKeyColumn,
  timestampColumns,
  versionColumn,
} from './_shared';
import { institutions, organizations } from './tenancy';

// ─────────────────────────────────────────────────────────────────────────────────────
// Enumerations. Each set is closed: adding a document kind, a page size or a request status
// changes the renderer and the state machine as well as the schema. What a school invents
// for itself — the wording, the letterhead, the variable list — lives in a template row.
// ─────────────────────────────────────────────────────────────────────────────────────

export const documentKindEnum = pgEnum('document_kind', [
  'transfer_certificate',
  'testimonial',
  'character_certificate',
  'admission_letter',
  'id_card',
  'fee_receipt',
  'marksheet',
  'salary_certificate',
  'experience_letter',
  'notice',
  'custom',
]);

export const documentPageSizeEnum = pgEnum('document_page_size', ['a4', 'a5', 'letter']);

export const documentOrientationEnum = pgEnum('document_orientation', ['portrait', 'landscape']);

/** Whose record the document is about. Drives which module's scope rules the renderer uses. */
export const documentSubjectKindEnum = pgEnum('document_subject_kind', [
  'student',
  'employee',
  'guardian',
]);

/**
 * `draft` may be edited; `pending_approval` awaits a second person; `approved` may be issued;
 * `issued` is terminal for the request (the document itself carries on); `revoked` records
 * that the issued document was withdrawn. There is no `deleted`.
 */
export const documentRequestStatusEnum = pgEnum('document_request_status', [
  'draft',
  'pending_approval',
  'approved',
  'rejected',
  'issued',
  'revoked',
]);

/** How a verification reached us. `public_web` is the unauthenticated employer check. */
export const documentVerificationChannelEnum = pgEnum('document_verification_channel', [
  'public_web',
  'qr_scan',
  'staff_portal',
]);

// ─────────────────────────────────────────────────────────────────────────────────────
// Templates
// ─────────────────────────────────────────────────────────────────────────────────────

/**
 * One version of one named template.
 *
 * `body_html`, `header_html` and `footer_html` are HTML with `{{placeholder}}` markers. The
 * renderer performs **allow-listed substitution only** — no expressions, no property
 * traversal, no evaluation of any kind — and HTML-escapes every substituted value, so a
 * script tag arriving through a student's name renders as inert text.
 *
 * `variables` is the declared allow-list for this template: an array of the placeholder names
 * the body may use. It is validated against the renderer's fixed variable map when the
 * template is saved, so an unresolvable placeholder is a save-time error rather than a blank
 * on a printed certificate.
 *
 * `requires_approval` makes issuance a two-person act. The database, not the service, is what
 * guarantees the two people differ (see `document_requests`).
 */
export const documentTemplates = pgTable(
  'document_templates',
  {
    id: primaryKeyColumn(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'restrict' }),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'restrict' }),
    /** Stable machine name; the version number distinguishes editions of it. */
    key: varchar('key', { length: 64 }).notNull(),
    name: varchar('name', { length: 128 }).notNull(),
    nameBn: varchar('name_bn', { length: 128 }),
    kind: documentKindEnum('kind').notNull(),
    bodyHtml: text('body_html').notNull(),
    pageSize: documentPageSizeEnum('page_size').notNull().default('a4'),
    orientation: documentOrientationEnum('orientation').notNull().default('portrait'),
    /** `{ top, right, bottom, left }` in millimetres. */
    margins: jsonb('margins')
      .notNull()
      .default(sql`'{"top":20,"right":18,"bottom":20,"left":18}'::jsonb`),
    headerHtml: text('header_html'),
    footerHtml: text('footer_html'),
    /** Declared placeholder allow-list: `["student.fullNameEn", …]`. */
    variables: jsonb('variables')
      .notNull()
      .default(sql`'[]'::jsonb`),
    requiresApproval: boolean('requires_approval').notNull().default(false),
    /**
     * The template's own edition number, not an optimistic lock. An active template is
     * immutable; editing supersedes it with `version + 1` and deactivates this row.
     */
    version: integer('version').notNull().default(1),
    isActive: boolean('is_active').notNull().default(true),
    ...timestampColumns(),
    ...archiveColumns(),
    ...actorColumns(),
  },
  (table) => [
    // Not partial: a version number is never reused, archived or not.
    uniqueIndex('document_templates_institution_key_version_key').on(
      table.institutionId,
      table.key,
      table.version,
    ),
    // At most one live edition of a key at a time.
    uniqueIndex('document_templates_active_key')
      .on(table.institutionId, table.key)
      .where(sql`${table.isActive} AND ${table.archivedAt} IS NULL`),
    index('document_templates_tenant_idx').on(table.tenantId),
    index('document_templates_institution_kind_idx').on(table.institutionId, table.kind),
  ],
);

// ─────────────────────────────────────────────────────────────────────────────────────
// Requests
// ─────────────────────────────────────────────────────────────────────────────────────

/**
 * Somebody asking for a document to be produced for a subject.
 *
 * `template_version` is captured at request time so an approval granted against one edition
 * of the wording cannot be spent on a different edition approved by nobody.
 *
 * The four-eyes rule lives in migration 0028 as
 * `document_requests_approver_not_requester` — a check constraint. The service refuses a
 * self-approval with a readable message, and the database refuses it regardless of who is
 * asking.
 */
export const documentRequests = pgTable(
  'document_requests',
  {
    id: primaryKeyColumn(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'restrict' }),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'restrict' }),
    templateId: uuid('template_id')
      .notNull()
      .references(() => documentTemplates.id, { onDelete: 'restrict' }),
    templateVersion: integer('template_version').notNull(),
    subjectKind: documentSubjectKindEnum('subject_kind').notNull(),
    /** No FK: polymorphic by `subject_kind`. See the module comment. */
    subjectId: uuid('subject_id').notNull(),
    requestedBy: uuid('requested_by').notNull(),
    purpose: varchar('purpose', { length: 500 }).notNull(),
    status: documentRequestStatusEnum('status').notNull().default('draft'),
    approvedBy: uuid('approved_by'),
    approvedAt: timestamp('approved_at', { withTimezone: true, mode: 'date' }),
    rejectionReason: varchar('rejection_reason', { length: 1000 }),
    version: versionColumn(),
    ...timestampColumns(),
    ...archiveColumns(),
    ...actorColumns(),
  },
  (table) => [
    index('document_requests_tenant_idx').on(table.tenantId),
    index('document_requests_institution_status_idx').on(table.institutionId, table.status),
    index('document_requests_subject_idx').on(table.subjectKind, table.subjectId),
    index('document_requests_template_idx').on(table.templateId),
    index('document_requests_requested_by_idx').on(table.requestedBy),
  ],
);

// ─────────────────────────────────────────────────────────────────────────────────────
// Issued documents
// ─────────────────────────────────────────────────────────────────────────────────────

/**
 * A document that exists in the world.
 *
 * Immutable by trigger. `rendered_html` is the exact markup that was printed;
 * `data_snapshot` is the exact variable map it was rendered from, so the assertion the
 * certificate makes survives every later change to the student's record. `storage_key`
 * points at the archived bytes in object storage; it is nullable because the row is the
 * record and the object is a convenience.
 *
 * `request_id` is nullable: a bulk issuance for a section produces documents with no
 * individual request behind them.
 */
export const issuedDocuments = pgTable(
  'issued_documents',
  {
    id: primaryKeyColumn(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'restrict' }),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'restrict' }),
    requestId: uuid('request_id').references(() => documentRequests.id, { onDelete: 'restrict' }),
    templateId: uuid('template_id')
      .notNull()
      .references(() => documentTemplates.id, { onDelete: 'restrict' }),
    templateVersion: integer('template_version').notNull(),
    subjectKind: documentSubjectKindEnum('subject_kind').notNull(),
    subjectId: uuid('subject_id').notNull(),
    /** `TC-2026-000042`. Server-generated, never reused. */
    serialNumber: varchar('serial_number', { length: 48 }).notNull(),
    issuedOn: date('issued_on').notNull(),
    issuedBy: uuid('issued_by').notNull(),
    renderedHtml: text('rendered_html').notNull(),
    storageKey: varchar('storage_key', { length: 512 }),
    /** What the document asserted, frozen. The reason this module exists. */
    dataSnapshot: jsonb('data_snapshot')
      .notNull()
      .default(sql`'{}'::jsonb`),
    /** High-entropy, unguessable, from `humanCode` — never `Math.random`. */
    verificationCode: varchar('verification_code', { length: 32 }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true, mode: 'date' }),
    revokedBy: uuid('revoked_by'),
    revokedReason: varchar('revoked_reason', { length: 1000 }),
    ...timestampColumns(),
    ...archiveColumns(),
    ...actorColumns(),
  },
  (table) => [
    // Not partial: a serial number is never reused.
    uniqueIndex('issued_documents_institution_serial_key').on(
      table.institutionId,
      table.serialNumber,
    ),
    uniqueIndex('issued_documents_institution_verification_key').on(
      table.institutionId,
      table.verificationCode,
    ),
    // Globally unique as well: the public endpoint resolves a code with no tenant in hand.
    uniqueIndex('issued_documents_verification_code_key').on(table.verificationCode),
    index('issued_documents_tenant_idx').on(table.tenantId),
    index('issued_documents_subject_idx').on(table.subjectKind, table.subjectId),
    index('issued_documents_institution_issued_idx').on(table.institutionId, table.issuedOn),
    index('issued_documents_template_idx').on(table.templateId),
    index('issued_documents_request_idx').on(table.requestId),
  ],
);

// ─────────────────────────────────────────────────────────────────────────────────────
// Verifications
// ─────────────────────────────────────────────────────────────────────────────────────

/**
 * One check of one verification code. Append-only.
 *
 * Recorded even for an unauthenticated caller, because "who has been checking this
 * certificate" is exactly the question a school asks when a forgery surfaces. Only the
 * client IP is kept — no name, no session, nothing that would turn a public convenience into
 * a tracking surface.
 */
export const documentVerifications = pgTable(
  'document_verifications',
  {
    id: primaryKeyColumn(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'restrict' }),
    institutionId: uuid('institution_id')
      .notNull()
      .references(() => institutions.id, { onDelete: 'restrict' }),
    issuedDocumentId: uuid('issued_document_id')
      .notNull()
      .references(() => issuedDocuments.id, { onDelete: 'restrict' }),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'date' })
      .notNull()
      .defaultNow(),
    verifierIp: varchar('verifier_ip', { length: 64 }),
    channel: documentVerificationChannelEnum('channel').notNull().default('public_web'),
    ...timestampColumns(),
    ...archiveColumns(),
    ...actorColumns(),
  },
  (table) => [
    index('document_verifications_tenant_idx').on(table.tenantId),
    index('document_verifications_document_idx').on(table.issuedDocumentId, table.verifiedAt),
    index('document_verifications_institution_idx').on(table.institutionId, table.verifiedAt),
  ],
);

// ─────────────────────────────────────────────────────────────────────────────────────

export const documentTemplatesRelations = relations(documentTemplates, ({ one, many }) => ({
  institution: one(institutions, {
    fields: [documentTemplates.institutionId],
    references: [institutions.id],
  }),
  requests: many(documentRequests),
  issued: many(issuedDocuments),
}));

export const documentRequestsRelations = relations(documentRequests, ({ one, many }) => ({
  institution: one(institutions, {
    fields: [documentRequests.institutionId],
    references: [institutions.id],
  }),
  template: one(documentTemplates, {
    fields: [documentRequests.templateId],
    references: [documentTemplates.id],
  }),
  issued: many(issuedDocuments),
}));

export const issuedDocumentsRelations = relations(issuedDocuments, ({ one, many }) => ({
  institution: one(institutions, {
    fields: [issuedDocuments.institutionId],
    references: [institutions.id],
  }),
  request: one(documentRequests, {
    fields: [issuedDocuments.requestId],
    references: [documentRequests.id],
  }),
  template: one(documentTemplates, {
    fields: [issuedDocuments.templateId],
    references: [documentTemplates.id],
  }),
  verifications: many(documentVerifications),
}));

export const documentVerificationsRelations = relations(documentVerifications, ({ one }) => ({
  issuedDocument: one(issuedDocuments, {
    fields: [documentVerifications.issuedDocumentId],
    references: [issuedDocuments.id],
  }),
}));
